# 01: Flavour

In this example, we will see how non-diagonal flavour couplings at the low scale arise from the Renormalization Group evolution of lepton-diagonal couplings

In [9]:
from alpaca.rge.classes import ALPcouplings
import numpy as np

## From quark couplings

In [3]:
ac1 = ALPcouplings({'cuR': 1.0}, scale=1000, basis='derivative_above')

In [5]:
ac2 = ac1.match_run(scale_out=5, basis='RL_below', integrator='leadinglog')

In [10]:
print(np.real(ac2['cdL']))

[[ 1.68331826e-02 -2.82849209e-06  6.79746226e-05]
 [-2.82849209e-06  1.68464893e-02 -3.33792006e-04]
 [ 6.79746226e-05 -3.33792006e-04  2.48863446e-02]]


In [11]:
print(np.imag(ac2['cdL']))

[[-5.29395592e-23 -1.17858945e-06  2.71641287e-05]
 [ 1.17858945e-06  5.29395592e-23  6.25227006e-06]
 [-2.71641287e-05 -6.25227006e-06  0.00000000e+00]]


## From $W$ couplings

In [12]:
ac3 = ALPcouplings({'cW': 1.0}, scale=1000, basis='derivative_above')

In [13]:
ac4 = ac3.match_run(scale_out=5, basis='RL_below', integrator='leadinglog')

In [14]:
print(np.real(ac4['cdL']))

[[ 4.84466754e-05  8.12973576e-09 -1.97632437e-07]
 [ 8.12973576e-09  4.84083734e-05  9.70479401e-07]
 [-1.97632437e-07  9.70479401e-07  2.50330157e-05]]


In [15]:
print(np.imag(ac4['cdL']))

[[ 1.03396270e-24  3.42667556e-09 -7.89765659e-08]
 [-3.42667556e-09 -4.20183357e-26 -1.81777528e-08]
 [ 7.89765659e-08  1.81777528e-08 -1.30701958e-29]]
